### ISSUE TITLE
parallelization of treenode calculations

### ISSUE THREAD

**Issue by MathiasMichel** [ComPWA/ComPWA#17]
use pstl

**Comment by spflueger** [comment]
PR #305 fixes this for all primitive operations. Unfortunately all custom Strategies like BreitWigner Strategy etc cannot be multithreaded with pstl because the have more than 2 ingoing data streams. Therefore the multithreading is not used for the most crucial calculations and there is not significant increase in speed.
To solve this, custom strategies should be converted into a tree itself made up of only trivial operations. This is however extremely tedious and not pursued any further
