### ISSUE TITLE
Methods to extract intensity of components(e.g., partial waves, resoanances) 

### ISSUE THREAD

**Issue by zhang-jingqing** [ComPWA/ComPWA#171]
Take the process Jpsi -> gamma f_0 as an example, it can happens in LS=(0,1), (2,1).  

Some times we want to know the fit fractions/yields of partial waves a_01 and a_21.
And some times for Jpsi-> gamma f_0, both f_0(980) and f_0(1500) may appear,
we want to know the fit fractions/yields of f_0(980) and f_0(1500).

We need tools to extract such component intensity. It needs both incoherent sum
and coherent sum of the basic sequential decay amplitudes.

**Comment by spflueger** [comment]
My work currently crosses paths with this issue. I think the only reasonable way would be, that the XML builder is able to create also components of a full amplitude (that seems fairly easy).
The other possibilities I considered are
- Making it part of the Intensity interface. However since the components might be not only of type intensity would make the interface instable. Also the idea was to have intensity to be simply a function (without any logic).
- Use the evaluate() method of the Intensity interface to specify components to be evaluated. It makes the interface too complicated plus the disadvantage from the point above also exists

What do you think? Any other ideas?

**Comment by zhang-jingqing** [comment]
If the XML builder can create components of a full intensity it would be very good, then what we needed is to update the this components' parameters according to fit result (and it seems easy, no matter update the xml before create component or update components' parameter after creation)

**Comment by spflueger** [comment]
Yeah, I don't see any issues in that regard
