### ISSUE TITLE
Spin SetDenominator in operator+ or operator-

### ISSUE THREAD

**Issue by Leongrim** [ComPWA/ComPWA#199]
By adding/subtracting spins it might happen that the denominator is not equal to 1 or 2.
This results that SetDenominator throws an error.

At this point SetDenominator shoundn´t throw the error, since simplify later on reduces the denominator again.

**Comment by spflueger** [comment]
I suggest we remove this functionality from `ComPWA::Spin` and use the qft++ Spin for this. These operators + and - are kind of akward anyways (since it is not clear what this operation really does). Why was the qft++ code modified to use ComPWA classes?
At this point we can also refactor the Spin class a bit. I think we simply need a constructor and a getter. Most of the other functions are not required and can be safely removed.

**Comment by hansgans** [comment]
I think the Core module should not depend on a third party library (I know it depends on boost). Probably at some point in the future we could remove the QFT++ dependency.

**Comment by spflueger** [comment]
Hmm yeah I agree. At least no "non-standard" third party code. But does the Core module use any qft++ stuff? Afaik it's only used in the helicity formalism for boosting/rotating and the WignerD functions.

**Comment by spflueger** [comment]
I dug a bit deeper here. I think the main problem is that we use Spin as a `magnitude` and a `projection` (both being fractions), but in the helicity formalism (and the WignerD functions) only the projection or the magnitude are used separately.

Therefore it would be useful if we define a Fraction class which is either a `magnitude` or a `projection`.

We would still keep the Spin class since that would be still useful in cases like the Clebsch Gordan coefficients.

I will upload a proposal pull request later

**Comment by spflueger** [comment]
It was discussed in pull request #202, to abolish the Spin class as a whole
