### ISSUE TITLE
Events outs of PHSP by 3e-15

### ISSUE THREAD

**Issue by sebastianJaeger** [ComPWA/ComPWA#203]
When i try to generate events in the canonical formalism for my decay J/Psi -> p pbar eta as shown in the quickstart notebook, the check HelicityKinematics::isWithinPhaseSpace(point) fails. The event lies 3.55271367880050092935562133789e-15 GeV above the upper PHSP boundary, which is 16 times the machine epsilon. Modelfile is attached. For this model to work the following modification in the Spin classs is necessary:

  void SetDenominator(unsigned int denom) {
    /*if (denom != 1 && denom != 2)
      throw BadParameter("Spin::SetDenominator() | "+ std::to_string(denom) +
                         " Should be equal 1 oder 2!");*/
    J_denominator_ = denom;
  }

[model.txt](https://github.com/ComPWA/ComPWA/files/3457325/model.txt)

**Comment by spflueger** [comment]
It was traced back to a problem we had before. The fixed initial state invariant mass (here a J/psi) is always generate slightly above the actual invariant mass boundary.
Currently we added one machine precision * value on the upper invariant mass boundary.

What is the best way to solve this?
The tricky part in solving this nicely lies in the difference of the the initial state SubSystem and the rest of them. Normally you want to shrink the phase space boundary a little bit, to avoid numerical errors to move your event outside of the boundary where the Intensity might give `nan` or `inf`. However for a fix initial state invariant mass (decay of a particle), the interval has to be widened since all events are generated at the upper edge. And with numerical errors you will often be above that upper edge.

I only can come up with one good solution right now.
We should avoid creating and checking such boundaries for the initial state reaction in the first place, since they should always be correct anyways. For the other subsystems, we can cut one machine precision, but in the opposite way (so shrinking the phase space).

**Comment by spflueger** [comment]
Ok, apparently there were was a mistake in the model file, which resulted in a Zero Intensity. This was the actual reason for the event generation to get stuck in an endless loop. The expert system does not create this kind of model file though, so I don't see a problem there. 
Nevertheless it sometimes (depends on the reaction, but well below the percent level) happens that events are generated outside the phase space boundary. This is "normal" since the algorithms of the event generators (both EvtGen and TGenPhaseSpace) are just not able to produce this kind of precise result.
I would leave things as they are, since only a few events near the boundary are lost. Artificially adjusting these boundaries is a bit tricky and is not solving the actual problem. To really solve the problem, the event generators would need numerical stabilization. However, this is far beyond simple and might not even be possible.
Btw, because the `EvtGenGenerator` produces far more stable and precise results than the RootGenerator, it is highly recommended to use the former.
I will close the issue, but feel free to reopen it in case experience further problems.
